url: "https://guide.pdis.run"
sass:
  sass_dir: assets
  style: :compressed
timezone: Asia/Taipei
collections:
  technology:
    name: "技術文件"
    output: true
  components:
    name: "共用元件"
    output: true
