name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
      - uses: ruby/setup-ruby
      - name: Setup Node
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install && npm install -g @lhci/cli@0.11.x
      - run: gem install github-pages
      - run: jekyll serve --baseurl=/manual
      - run: lhci autorun --url http://localhost:4000/manual

